### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by jayrulez** [Tsimiii/Bamboo#1]
What's the intension for this project?

Just a hobby or otherwise?

**Comment by Tsimiii** [comment]
Just a hobby project. Why?

**Comment by jayrulez** [comment]
I was just wondering about contributing.

**Comment by Tsimiii** [comment]
What you should know, I'm totally new to ASP.NET Core and Angular 2. I will start a new job using ASP.NET and Angular 2 in September, so currently I don't really have any experiences in these technologies. If you have more experiences and want to join my project, I would be happy to recieve you help and advices.

**Comment by jayrulez** [comment]
No problem. I'd be happy to help with it.

Let's get started

**Comment by jayrulez** [comment]
Add the project root folder to git so I can checkout the whole solution please.

**Comment by Tsimiii** [comment]
Something happened during commit and now I can't open my src/Bamboo folder here in github. I can't handle this problem now because I'm not home, little bit later I will resolve it.

**Comment by Tsimiii** [comment]
Okey, now it's working. I haven't done much work yet, basically I've created a mini-Registration page without Angular 2 yet (model-view-controller) and after clicking the Register button the datas are saved in the database.

**Comment by jayrulez** [comment]
Great. Now let's define some of the basic features that we should start out with as well as the storage requirements.

For e.g: 
Registration
Login
Connect with facebook/google
Verify Email

And so forth.

We can use user stories if that's convenient for you.

I will close this issue and open a new one for this.
